Base.Server/Base.Web/Base.Web/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Base.Web.ApplicationServices;
using Base.Web.ApplicationServices.Interfaces;
using Base.Web.Controllers.Base;
using Base.Web.Controllers.CustomActionResult;

namespace Base.Web.Controllers
{
    public class CustomerController : BaseController
    {
        readonly ICustomerAppService _customerAppService = new CustomerAppService();
        //
        // GET: /Customer/
        public ActionResult Index()
        {
            return View();
        }

        #region partialview
        public ActionResult List()
        {
            return PartialView("_List");
        }

        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        #endregion

        #region methods

        [HttpGet]
        public JsonNetResult GetCustomers()
        {
            var customers = _customerAppService.GetActiveCustomers().ToList();

            return new JsonNetResult()
            {
                Data = new { Customers = customers, Count = customers.Count() }
            };
        }

        #endregion
    }
}

Base.Server/Base.Web/Base.Web/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Base.Web.ApplicationServices;
using Base.Web.ApplicationServices.Interfaces;
using Base.Web.Controllers.Base;
using Base.Web.Controllers.CustomActionResult;

namespace Base.Web.Controllers
{
    public class GroupController : BaseController
    {
        readonly IGroupAppService _groupAppService = new GroupAppService();
        //
        // GET: /Group/
        public ActionResult Index()
        {
            return View();
        }

        #region partialview
        public ActionResult List()
        {
            return PartialView("_List");
        }

        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        #endregion

        #region methods

        [HttpGet]
        public JsonNetResult GetGroups()
        {
            var groups = _groupAppService.GetActiveGroups().ToList();

            return new JsonNetResult()
            {
                Data = new { Groups = groups, Count = groups.Count() }
            };
        }

        #endregion
    }
}

Base.Server/Base.Web/Base.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Base.Web.ApplicationServices;
using Base.Web.ApplicationServices.Interfaces;
using Base.Web.Controllers.Base;
using Base.Web.Controllers.CustomActionResult;

namespace Base.Web.Controllers
{
    public class UserController : BaseController
    {
        readonly IUserAppService _userAppService = new UserAppService();
        //
        // GET: /User/
        public ActionResult Index()
        {
            return View();
        }

        #region partialview
        public ActionResult List()
        {
            return PartialView("_List");
        }

        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        #endregion

        #region methods

        [HttpGet]
        public JsonNetResult GetUsers()
        {
            var users = _userAppService.GetActiveUsers().ToList();

            return new JsonNetResult()
            {
                Data = new { Users = users, Count = users.Count() }
            };
        }

        #endregion
    }
}

Base.Server/Base.Web/Base.Web/Views/Shared/_DisplayMenu.cshtml
@using Base.Web.Controllers.Base
@*<ul class="nav navbar-nav" ng-app="app.Menu" ng-controller="menuDisplayCtrl" ng-bind-html="htmlString | sanitize"></ul>*@
<ul class="nav navbar-nav">
    @Html.Raw(MenuHelper.GenerateMenuItems())
</ul>

Base.Server/Base.Web/Base.Web/Views/Shared/_Layout.cshtml
@using Base.Web.Controllers.Base
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Base</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
            @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/angularMenu")


    <style>
        .dropdown-submenu {
            position: relative;
        }

            .dropdown-submenu > .dropdown-menu {
                top: 0;
                left: 100%;
                margin-top: -6px;
                margin-left: -1px;
                -webkit-border-radius: 0 6px 6px 6px;
                -moz-border-radius: 0 6px 6px;
                border-radius: 0 6px 6px 6px;
            }

            .dropdown-submenu:hover > .dropdown-menu {
                display: block;
            }

            .dropdown-submenu > a:after {
                display: block;
                content: " ";
                float: right;
                width: 0;
                height: 0;
                border-color: transparent;
                border-style: solid;
                border-width: 5px 0 5px 5px;
                border-left-color: #ccc;
                margin-top: 5px;
                margin-right: -10px;
            }

            .dropdown-submenu:hover > a:after {
                border-left-color: #fff;
            }

            .dropdown-submenu.pull-left {
                float: none;
            }

                .dropdown-submenu.pull-left > .dropdown-menu {
                    left: -100%;
                    margin-left: 10px;
                    -webkit-border-radius: 6px 0 6px 6px;
                    -moz-border-radius: 6px 0 6px 6px;
                    border-radius: 6px 0 6px 6px;
                }
        
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Base", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_DisplayMenu")
                @*<ul class="nav navbar-nav">
                        @if (Session["UserSession"] != null)
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Customer<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Customer Management", "Index", "Customer")</li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("User Management", "Index", "User")</li>
                                    <li>@Html.ActionLink("Group Management", "Index", "Group")</li>
                                </ul>
                                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                                    <li><a href="#">Some action</a></li>
                                    <li><a href="#">Some other action</a></li>
                                    <li class="dropdown-submenu">
                                        <a tabindex="-1" href="#">Hover me for more options</a>
                                        <ul class="dropdown-menu">
                                            <li><a tabindex="-1" href="#">Second level</a></li>
                                            <li class="dropdown-submenu">
                                                <a href="#">Even More..</a>
                                                <ul class="dropdown-menu">
                                                    <li>@Html.ActionLink("User Management", "Index", "User")</li>
                                                    <li>@Html.ActionLink("Group Management", "Index", "Group")</li>
                                                </ul>
                                            </li>
                                            <li>@Html.ActionLink("User Management", "Index", "User")</li>
                                            <li>@Html.ActionLink("Group Management", "Index", "Group")</li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>

                        }
                    </ul>*@
                @Html.Partial("_LoginPartial")
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>